var Languages = {
	"cn": {"credit0-name": "Louiz","credit0-url": "http://userscripts.org/users/349372","download-button-tip": "保存到本地","download-button-text": "下载","menu-button-tip": "选择下载格式","group-options": "选项","group-high-definition": "标准分辨率","group-standard-definition": "较高分辨率","group-mobile": "Mobile","group-unknown": "未知格式","group-update": "已推出新版YouTube下载插件！","option-check": "检查更新","option-format": "标题格式","button-options": "选项","button-options-close": "close","button-update": "更新请点击这里","error-no-downloads": "下载格式不可用"},
	"cs": {"credit0-name": "janwatzek","credit0-url": "http://userscripts.org/users/janwatzek","download-button-tip": "Uložit video na pevný disk","download-button-text": "Stáhnout","menu-button-tip": "Vyberte formát ke stažení","group-options": "Nastavení","group-high-definition": "Vysoké rozlišení","group-standard-definition": "Standardní rozlišení","group-mobile": "Mobile","group-unknown": "Neznámý formát","group-update": "Nová verze skriptu YouTube Video Download je dostupná ke stažení!","option-check": "Kontrolovat aktualizace","option-format": "Formát názvu videa","button-options": "nastavení","button-options-close": "close","button-update": "Klikněte sem pro aktualizaci","error-no-downloads": "Žádné formáty nejsou dostupné ke stažení"},
	"de": {"credit0-name": "QuHno","credit0-url": "http://userscripts.org/users/348658","download-button-tip": "Video auf der Festplatte speichern","download-button-text": "Download","menu-button-tip": "Download Format wählen","group-options": "Einstellungen","group-high-definition": "HD","group-standard-definition": "Standard Auflösung","group-mobile": "Mobile","group-unknown": "Unbekanntes Format","group-update": "Eine neue Version von YouTube Video Download steht zur Verfügung","option-check": "Auf neue Version überprüfen","option-format": "Titel Format","button-options": "einstellungen","button-options-close": "close","button-update": "Hier klicken um jetzt upzudaten","error-no-downloads": "Keine Download Formate vorhanden"},
	"en": {"download-button-tip": "Download this video","download-button-text": "Download","menu-button-tip": "Choose from additional formats","group-options": "Options","group-high-definition": "High definition","group-standard-definition": "Standard definition","group-mobile": "Mobile","group-unknown": "Unknown formats","group-update": "An update is available","option-check": "Check for updates","option-format": "Title format","button-options": "options","button-options-close": "close","button-update": "Click here to update YouTube Video Download","error-no-downloads": "No downloadable streams found"},
};
function T(item) { return Languages.current[item] || Languages.en[item]; }
if (Languages[document.documentElement.getAttribute("lang")])
Languages.current = Languages[document.documentElement.getAttribute("lang")];
else
Languages.current = Languages.en;
