var Languages = {
	"cs": {"credit0-name": "janwatzek","credit0-url": "http://userscripts.org/users/janwatzek","download-button-tip": "Uložit video na pevný disk","download-button-text": "Stáhnout","menu-button-tip": "Vyberte formát ke stažení","group-options": "Nastavení","group-high-definition": "Vysoké rozlišení","group-standard-definition": "Standardní rozlišení","group-mobile": "Mobile","group-unknown": "Neznámý formát","group-update": "Nová verze skriptu YouTube Video Download je dostupná ke stažení!","option-check": "Kontrolovat aktualizace","option-format": "Formát názvu videa","button-options": "nastavení","button-options-close": "close","button-update": "Klikněte sem pro aktualizaci","error-no-downloads": "Žádné formáty nejsou dostupné ke stažení"},
	"de": {"credit0-name": "QuHno","credit0-url": "http://userscripts.org/users/348658","download-button-tip": "Video auf der Festplatte speichern","download-button-text": "Download","menu-button-tip": "Download Format wählen","group-options": "Einstellungen","group-high-definition": "HD","group-standard-definition": "Standard Auflösung","group-mobile": "Mobile","group-unknown": "Unbekanntes Format","group-update": "Eine neue Version von YouTube Video Download steht zur Verfügung","option-check": "Auf neue Version überprüfen","option-format": "Titel Format","button-options": "einstellungen","button-options-close": "close","button-update": "Hier klicken um jetzt upzudaten","error-no-downloads": "Keine Download Formate vorhanden"},
	"en": {"download-button-tip": "Download this video","download-button-text": "Download","menu-button-tip": "Choose from additional formats","group-options": "Options","group-high-definition": "High definition","group-standard-definition": "Standard definition","group-mobile": "Mobile","group-unknown": "Unknown formats","group-update": "An update is available","option-check": "Check for updates","option-format": "Title format","button-options": "options","button-options-close": "close","button-update": "Click here to update YouTube Video Download","error-no-downloads": "No downloadable streams found"},
	"fr": {"credit0-name": "jok-r","credit0-url": "http://userscripts.org/users/87056","download-button-tip": "Télécharger cette vidéo","download-button-text": "Télécharger","menu-button-tip": "Choisissez le format à télécharger","group-options": "Options","group-high-definition": "Haute définition","group-standard-definition": "Définition standard","group-mobile": "Mobile","group-unknown": "Format inconnu","group-update": "Une nouvelle version de YouTube Video Download est disponible","option-check": "Vérifier les mises à jour","option-format": "Format du nom de fichier","button-options": "options","button-options-close": "close","button-update": "Cliquer ici pour mettre à jour maintenant","error-no-downloads": "Pas de formats de téléchargement disponible"},
	"it": {"credit0-name": "Kharg","credit0-url": "http://userscripts.org/users/kharg","download-button-tip": "Salva il video nell'HD","download-button-text": "Scarica","menu-button-tip": "Scegli un formato da scaricare","group-options": "Opzioni","group-high-definition": "Alta definizione","group-standard-definition": "Qualità standard","group-mobile": "Mobile","option-check": "Controlla la disponibilità di aggiornamenti","option-format": "Formato titolo","button-options": "opzioni","button-options-close": "close","error-no-downloads": "Nessun formato da scaricare disponibile"},
	"ja": {"credit0-name": "K-M","credit0-url": "http://userscripts.org/users/184613","download-button-tip": "ハードディスクにビデオを保存","download-button-text": "ダウンロード","menu-button-tip": "ダウンロードする形式を選択","group-options": "オプション","group-high-definition": "高画質","group-standard-definition": "普通の画質","group-mobile": "Mobile","group-unknown": "不明な形式","group-update": "YouTube Video Downloadの更新があります","option-check": "更新を確認","option-format": "タイトルの形式","button-options": "オプション","button-options-close": "close","button-update": "ここをクリックすると更新します","error-no-downloads": "ダウンロードできません"},
	"pl": {"credit0-name": "look997","credit0-url": "http://userscripts.org/users/123591","download-button-tip": "Zapisz film na twardym dysku","download-button-text": "Pobierz","menu-button-tip": "Wybierz format do pobrania","group-options": "Opcje","group-high-definition": "Wysoka rozdzielczość","group-standard-definition": "Standardowa rozdzielczość","group-mobile": "Mobile","group-unknown": "Nieznany format","group-update": "Nowa wersja YouTube Video Download jest dostępna","option-check": "Sprawdzaj aktualizacje","option-format": "Format tytułu","button-options": "opcje","button-options-close": "close","button-update": "Kliknij tutaj, aby zaktualizować","error-no-downloads": "Nie dostępne formaty"},
	"pt-BR": {"credit0-name": "Gandalf","credit0-url": "http://userscripts.org/users/73303","download-button-tip": "Salvar vídeo para o disco","download-button-text": "Baixar","menu-button-tip": "Escolha um formato para baixar","group-options": "Opções","group-high-definition": "Definição alta","group-standard-definition": "Definição padrão","group-mobile": "Mobile","group-unknown": "Formato desconhecido","group-update": "Uma nova versão do Youtube Video Download está disponível","option-check": "Procurar por atualizações","option-format": "Formato do título","button-options": "opções","button-options-close": "close","button-update": "Clique aqui para atualizar agora","error-no-downloads": "Nenhum formato disponível para baixar"},
	"ru": {"credit0-name": "Gandalf","credit0-url": "http://userscripts.org/users/73303","download-button-tip": "Сохранить на жесткий диск","download-button-text": "Скачать","menu-button-tip": "Выберите формат для загрузки","group-options": "Настройки","group-high-definition": "Высокое разрешение","group-standard-definition": "Стандартное разрешение","group-mobile": "Mobile","group-unknown": "Неизвестный формат","group-update": "Доступна новая версия YouTube Video Download","option-check": "Проверить обновления","option-format": "Формат заголовка","button-options": "настройки","button-options-close": "close","button-update": "Нажмите тут для обновления","error-no-downloads": "Нет загружаемых допустимых форматов"},
	"sr": {"credit0-name": "titanicus","credit0-url": "http://userscripts.org/users/26334","download-button-tip": "Сачувај видео на диск","download-button-text": "Преузми","menu-button-tip": "Изаберите формат видеа за преузимање","group-options": "Опције","group-high-definition": "Висока резолуција","group-standard-definition": "Стандардна резолуција","group-mobile": "Mobile","group-unknown": "Непознат формат","group-update": "Ново издање YouTube Видео Преузимача је доступно","option-check": "Провери надоградње","option-format": "Формат наслова","button-options": "опције","button-options-close": "close","button-update": "Кликните овде да ажурирате сада","error-no-downloads": "Нема доступних формата"},
	"tr": {"credit0-name": "Kenterte","credit0-url": "http://userscripts.org/users/Kenterte","download-button-tip": "Videoyu Farklı Kaydet","download-button-text": "İndir","menu-button-tip": "Bir İndirme Formatı Seçin","group-options": "Ayarlar","group-high-definition": "Yüksek Çözünürlük","group-standard-definition": "Standart Çözünürlük","group-mobile": "Mobile","group-unknown": "Bilinmeyen Format","group-update": "YouTube Video Downloader'ın yeni bir versiyonu var","option-check": "Güncelleştirmeleri Kontrol Et","option-format": "Başlık Türü","button-options": "Ayarlar","button-options-close": "close","button-update": "Güncelleştirmek için tıklayınız","error-no-downloads": "Format Bulunamadı"},
	"zh-TW": {"credit0-name": "Wang Zheng","credit0-url": "http://userscripts.org/users/381783","download-button-tip": "儲存到硬碟","download-button-text": "下載","menu-button-tip": "選擇要下載的格式","group-options": "選項","group-high-definition": "HD","group-standard-definition": "標準畫質","group-mobile": "Mobile","group-unknown": "不明的格式","group-update": "有新的YouTube Video Download可供更新","option-check": "檢查更新","option-format": "標題格式","button-options": "選項","button-options-close": "close","button-update": "請點選此處更新","error-no-downloads": "沒有可用的下載格式"},
	"zh": {"credit0-name": "Louiz","credit0-url": "http://userscripts.org/users/349372","download-button-tip": "保存到本地","download-button-text": "下载","menu-button-tip": "选择下载格式","group-options": "选项","group-high-definition": "标准分辨率","group-standard-definition": "较高分辨率","group-mobile": "Mobile","group-unknown": "未知格式","group-update": "已推出新版YouTube下载插件！","option-check": "检查更新","option-format": "标题格式","button-options": "选项","button-options-close": "close","button-update": "更新请点击这里","error-no-downloads": "下载格式不可用"},
};
function T(item) { return Languages.current[item] || Languages.en[item]; }
if (Languages[document.documentElement.getAttribute("lang")] && yt && yt._config)
Languages.current = Languages[document.documentElement.getAttribute("lang") == "pt" ? (yt.config_.HL_LOCALE || document.documentElement.getAttribute("lang")) : document.documentElement.getAttribute("lang")];
else
Languages.current = Languages.en;
